import { and, eq, gt, isNull } from "drizzle-orm";
import { db } from "@/db";
import { passwordResetTokens, users } from "@/db/schema";
import { hashPassword } from "@/lib/auth/password";
import { destroyAllUserSessions } from "@/lib/auth/session";
import { hashToken } from "@/lib/auth/tokens";
import { jsonError, jsonOk } from "@/lib/auth/guards";
import { resetPasswordWithTokenSchema } from "@/lib/validators/auth";

/**
 * User-facing password reset using a one-time token generated by an admin.
 * POST /api/v1/auth/reset-password
 */
export async function POST(request: Request) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return jsonError(400, "INVALID_JSON", "请求体必须是 JSON");
  }

  const parsed = resetPasswordWithTokenSchema.safeParse(body);
  if (!parsed.success) {
    return jsonError(400, "VALIDATION_ERROR", "参数校验失败", parsed.error.flatten());
  }

  const { token, newPassword } = parsed.data;
  const tokenHash = hashToken(token);
  const now = new Date();

  const reset = await db.query.passwordResetTokens.findFirst({
    where: and(
      eq(passwordResetTokens.tokenHash, tokenHash),
      isNull(passwordResetTokens.usedAt),
      gt(passwordResetTokens.expiresAt, now),
    ),
  });

  if (!reset) {
    return jsonError(400, "INVALID_TOKEN", "重置令牌无效或已过期");
  }

  const passwordHash = await hashPassword(newPassword);

  await db.transaction(async (tx) => {
    await tx
      .update(users)
      .set({ passwordHash })
      .where(eq(users.id, reset.userId));

    await tx
      .update(passwordResetTokens)
      .set({ usedAt: now })
      .where(eq(passwordResetTokens.id, reset.id));
  });

  await destroyAllUserSessions(reset.userId);

  return jsonOk({ ok: true, message: "密码已重置，请重新登录" });
}
