import { and, eq, gt, isNull } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { passwordResetTokens, users } from "@/db/schema";
import { hashPassword } from "@/lib/auth/password";
import { destroyAllUserSessions } from "@/lib/auth/session";
import { hashToken } from "@/lib/auth/tokens";
import { jsonError, jsonOk, type ApiErrorBody } from "@/lib/auth/guards";
import { resetPasswordWithTokenSchema } from "@/lib/validators/auth";
import { verifyTurnstileToken } from "@/lib/security/turnstile";
import { firstZodMessage } from "@/lib/validators/format";
import {
  assertSameOrigin,
  getClientIp,
  ipBucketKey,
  readJsonBody,
} from "@/lib/security/request";
import {
  RESET_IP_POLICY,
  checkRateLimit,
  formatLockMessage,
  hitRateLimit,
  rateLimitHeaders,
  type RateLimitStatus,
} from "@/lib/security/rate-limit";

export const dynamic = "force-dynamic";
export const maxDuration = 30;

function lockedResponse(status: RateLimitStatus) {
  const body: ApiErrorBody = {
    error: {
      code: "TOO_MANY_ATTEMPTS",
      message: formatLockMessage(status.retryAfterSec),
      details: { retryAfterSec: status.retryAfterSec },
    },
  };
  return NextResponse.json(body, {
    status: 429,
    headers: rateLimitHeaders(status),
  });
}

/**
 * User-facing password reset using a one-time token generated by an admin.
 * POST /api/v1/auth/reset-password
 */
export async function POST(request: Request) {
  const originCheck = assertSameOrigin(request);
  if (!originCheck.ok) {
    return jsonError(originCheck.status, originCheck.code, originCheck.message);
  }

  const bodyResult = await readJsonBody(request);
  if (!bodyResult.ok) {
    return jsonError(bodyResult.status, bodyResult.code, bodyResult.message);
  }

  const parsed = resetPasswordWithTokenSchema.safeParse(bodyResult.data);
  if (!parsed.success) {
    return jsonError(
      400,
      "VALIDATION_ERROR",
      firstZodMessage(parsed.error),
      parsed.error.flatten(),
    );
  }

  const ip = getClientIp(request);
  const ipKey = ipBucketKey("reset", ip);
  const ipStatus = await checkRateLimit(ipKey, RESET_IP_POLICY);
  if (!ipStatus.allowed) return lockedResponse(ipStatus);

  const turnstile = await verifyTurnstileToken(parsed.data.turnstileToken, request);
  if (!turnstile.ok) {
    return jsonError(400, turnstile.code, turnstile.message);
  }

  const { token, newPassword } = parsed.data;
  const tokenHash = hashToken(token);
  const now = new Date();

  const reset = await db.query.passwordResetTokens.findFirst({
    where: and(
      eq(passwordResetTokens.tokenHash, tokenHash),
      isNull(passwordResetTokens.usedAt),
      gt(passwordResetTokens.expiresAt, now),
    ),
  });

  if (!reset) {
    const after = await hitRateLimit(ipKey, RESET_IP_POLICY);
    if (!after.allowed) return lockedResponse(after);
    return jsonError(400, "INVALID_TOKEN", "重置令牌无效或已过期");
  }

  const passwordHash = await hashPassword(newPassword);

  await db.transaction(async (tx) => {
    await tx
      .update(users)
      .set({ passwordHash })
      .where(eq(users.id, reset.userId));

    await tx
      .update(passwordResetTokens)
      .set({ usedAt: now })
      .where(eq(passwordResetTokens.id, reset.id));
  });

  await destroyAllUserSessions(reset.userId);

  return jsonOk({ ok: true, message: "密码已重置，请重新登录" });
}
